### ISSUE TITLE
Not able to access images from all 6 cameras on ladybug 3

### ISSUE THREAD

**Issue by sahibdhanjal** [ros-drivers/camera1394#63]
Hi,
I am working on a project where I need to use the [LadyBug 3](https://www.ptgrey.com/ladybug3-360-degree-firewire-spherical-camera-systems) for getting a 360deg view of the scene. I built this repo from source, however, I am able to access just 1 camera (default camera: 0) from it.

I also tried to get the following launch files to work, however, none are working in my case:
1. camera.launch - however the node runs perfectly using <code>rosrun camera1394 camera1394_node</code>
2. multicamera_example_1.launch
3. multicamera_example_2.launch

The camera remains inactive and the error received is that the camera could not be opened, with a dull green light, which according to the [manual](http://robots.engin.umich.edu/nclt/manuals/Ladybug3-Technical-Reference.pdf) means that the camera is idle. 

Is there any way in which I would be able to access all the cameras (or any other camera rather than default)? Any help on the same would be greatly appreciated.

**Comment by awesomebytes** [comment]
http://wiki.ros.org/camera1394/Tutorials/UsingMultipleIEEE1394Cameras follow that tutorial. You need to launch one node per camera I believe. Setting the GUID for each of them.
