### ISSUE TITLE
Where is camera1394/Camera1394Config.h?

### ISSUE THREAD

**Issue by mdforbes500** [ros-drivers/camera1394#64]
Does it exist, and if so, where? I have looked all over this directory and gone through the image_pipeline files and I can't find it. I am trying to see how you deal with `config_` for a class I am writing for the Raspberry Pi camera.

**Comment by awesomebytes** [comment]
It's automatically generated from the dynamic reconfigure server configuration file: 
https://github.com/ros-drivers/camera1394/blob/master/cfg/Camera1394.cfg

http://wiki.ros.org/dynamic_reconfigure

**Comment by mdforbes500** [comment]
Thank you!
